### ISSUE TITLE
Replace user's home path in project list with `~`

### ISSUE THREAD

**Issue by luthfisolahudin** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#14]
Replace user's home path in project list with `~`, just like in GNU/Linux, for simplicity. 😄

So, I'm thinking to introduce new [`RecentProject`](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/blob/ba4543462dab7da741654574ba8fef865cdce8c3/Flow.Launcher.Plugin.JetBrainsIDEProjects/RecentProjectsReader.cs#L222) property, let's say `DisplayPath`, to be placed as [`SubTitle`](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/blob/ba4543462dab7da741654574ba8fef865cdce8c3/Flow.Launcher.Plugin.JetBrainsIDEProjects/Main.cs#L51) for displaying project. `Path` for storing actual/absolute path of project and `DisplayPath` for storing path that get displayed to user.

**Comment by luthfisolahudin** [comment]
Maybe something like [this](https://github.com/luthfisolahudin/Flow.Launcher.Plugin.JetBrainsIDEProjects/commit/b6ef6d0e1294c90b07535d60531dbcf6ee0b8319).

**Comment by kenty02** [comment]
Since some people and I put our repositories outside of our home directory, I thought it would be nice to be able to set what replaces what on the options screen.

**Comment by luthfisolahudin** [comment]
Ah okay, maybe something like namespace aliasing?

Example:
- `~` for `C:/Users/[user]/`
- `@Code` for `C:/Users/[user]/Documents/Code`

**Comment by kenty02** [comment]
That is correct. But adding a GUI for configuration would take a bit of time. Of course it would be worth it just to replace it with ~.
