### ISSUE TITLE
Feature Request: Keeping the Launcherwindow open

### ISSUE THREAD

**Issue by geisterfurz007** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#15]
## Motivation

I frequently work on projects that are spread across multiple IDEs (e.g. backend in Rider and app in Android Studio), so currently I have to keep reopening Flow Launcher for each of the parts of the project. This becomes annoying very quickly.

## Feature Request

For instance through a pressed Ctrl-Key, I could indicate to the plugin that I would like to keep the Launcher window open so I can quickly select another project without having to re-launch Flow Launcher.

---
I am open to making a PR for this, just wanted to make sure you would be fine with such a change :)

**Comment by kenty02** [comment]
Sorry for the late reply. I think it's a good idea! But it's a bit of a hassle for the user to delete the query when searching for the next project, so I thought it would be useful to delete the query on the plugin side when the launcher is left open. (Using the [ChangeQuery method](https://www.flowlauncher.com/docs/#/API-Reference/Flow.Launcher.Plugin/IPublicAPI/ChangeQuery))
