### ISSUE TITLE
Feature Request: Searching by the project's path

### ISSUE THREAD

**Issue by geisterfurz007** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#16]
## Motivation

At my workplace, our projects are named by a fixed naming scheme to make it easier to jump into a new project quickly. This also means that if I wanted to open the app-part of a project, I currently have to search for "app" in this plugin. This however shows me all app-parts of all projects and I don't have a way of further narrowing my search down.

## Feature Request

Next to searching for the project's name, I'd like to be able to also search in the project's path. This way, I can for example search for "app projectname" and get a result for a project with the name "app" which contains "projectname" in the path. I would also be able to search "the other way around", i.e. "projectname app" and get the same result. Lastly, searching for just "projectname" would show me all projects that I have opened on paths matching the projectname.

---
I am open to making a PR for this, just wanted to make sure you would be fine with such a change :)

**Comment by kenty02** [comment]
Sorry for the late reply. I think it is good! I thought it would be even better if we could control in the settings screen whether the paths are included in the search.
