### ISSUE TITLE
Plugin can't find my projet

### ISSUE THREAD

**Issue by iglee42** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#19]
Hello, the plugin can't find my intellij project whereas Jetbrain toolbox is launched
Intellij is also recognize in Jetbrain toolbox and my projet also

**Comment by kenty02** [comment]
Sorry for the very late reply, as KarmaDeb suggested, if you are using the Community Edition of IntelliJ, it should be fixed in the latest release. you should be able to update from the Flow Launcher after few hours.
