### ISSUE TITLE
Error application icon not found 

### ISSUE THREAD

**Issue by FurkanTRN** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#22]
![image](https://github.com/user-attachments/assets/0aeec25f-1f36-455c-9958-e5cc397eb774)
I solved the application icon error. All you need to 
```csharp
var path = Path.GetFullPath(Path.Combine(tool.InstallLocation, tool.LaunchCommand));
            var icoFile =
                Directory.GetParent(path)
                    ?.GetFiles("*.ico")
                    .FirstOrDefault()
                    ?.FullName
                ?? throw new FileNotFoundException("Failed to determine application icon file.");
```
change

```csharp

            var path = Path.GetFullPath(Path.Combine(tool.InstallLocation, tool.LaunchCommand));
            var icoFile =
                Directory.GetParent(path)
                    ?.GetFiles("*.ico")
                    .FirstOrDefault()
                    ?.FullName
                ?? "icon.ico";

```

I fixed the problem as above. Also I convert icon.png to ico file(Without deleting the png file). 

![image](https://github.com/user-attachments/assets/6e57f7fc-d950-4a4f-b7ff-499231600d00)

**Comment by kenty02** [comment]
Thanks, fixed it with [708d1f](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/commit/708d1f35d315681e160fb6a745b7414e2606020c), I noticed that null handling is done separately, so there is no need to do fallback processing on that part.　The new release should be available in a few hours.
