### ISSUE TITLE
Support for Jetbrains Toolbox v2

### ISSUE THREAD

**Issue by michaeloyer** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#6]
Jetbrains Toolbox [updated to v2](https://blog.jetbrains.com/toolbox-app/2023/08/toolbox-app-2-0-overhauls-installations-and-updates/) this month which caused this plugin to stop working due to folder structure changes.

**Comment by kenty02** [comment]
Fixed by #7
